const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Solid: 0},
	{ornaments1: 0},
	{Audio: 0},
	{Health: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{player: 0},
	{object: 0},
	{trap2: 0},
	{Pathfinding: 0},
	{MoveTo: 0},
	{enemy: 0},
	{treeStar: 0},
	{christmasTree: 0},
	{score: 0},
	{scoreNumber: 0},
	{border: 0},
	{handle: 0},
	{Particles: 0},
	{ornament2: 0},
	{Particles2: 0},
	{health: 0},
	{healthnumber: 0},
	{christmasTreeOrdement: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	ornaments1: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	object: class extends self.ISpriteInstance {},
	trap2: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	treeStar: class extends self.ISpriteInstance {},
	christmasTree: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	scoreNumber: class extends self.ITextInstance {},
	border: class extends self.ISpriteInstance {},
	handle: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ornament2: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	health: class extends self.ITextInstance {},
	healthnumber: class extends self.ITextInstance {},
	christmasTreeOrdement: class extends self.ISpriteInstance {}
}